//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyGamesNew.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyGamesNewString : DbContext
    {
        public EasyGamesNewString()
            : base("name=EasyGamesNewString")
        {

        }
    
     
    
        public virtual DbSet<Client> Clients { get; set; }
        
        public virtual DbSet<TransactionTable> TransactionTables { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
    }
}
